name: Build main

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-publish:
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@v2
    strategy:
      fail-fast: false
      matrix:
        runner:
          - [ self-hosted, amd64, noble, medium ]
          - [ self-hosted, arm64, noble, medium ]
    with:
      runner: "${{ toJSON(matrix.runner) }}"
      init-build-script: 'download-models.sh'
      publish-channel: 'latest/edge' # Add track if needed, e.g., 24/latest/edge
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN_MAIN }}
